site_name: "Neuroweaver Lab"
theme:
  name: "material"

nav:
  - Beginners: index.md
  - Theory: theory.md
  - Practice: practices.md
  - Codex: codex.md
  - Brain Training: cognitive.md
  - About: about.md
  - License: license_page.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search
