site_name: "Neuroweaver Lab"
theme:
  name: "material"

nav:
  - The Neuroweaver Framework: index.md
  - The Practice of Neuroweaver: implementation_guide.md
  - AI Integration Guide: Third_Mind-TECS.md
  - About Neuroweaver: about.md
  - License: license_page.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.smartsymbols

plugins:
  - search
